#此工作流程将干净安装节点依赖项，构建源代码并跨不同版本的节点运行测试
#更多信息参见：https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

名称：中青看点

上：
  工作流调度：
  时间表：
     - cron : ' */12 * * * * '
  观看：
    类型：开始

工作：
  构建：
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    环境：
        YOUTH_HEADER : ${{ 秘密.YOUTH_HEADER }}
        YOUTH_ARTBODY : ${{ 秘密.YOUTH_ARTBODY }}
        YOUTH_REDBODY : ${{ 秘密.YOUTH_REDBODY }}
        YOUTH_TIME : ${{ 秘密.YOUTH_TIME }}
    步骤：
      -名称：结帐
        运行：|
          git clone https://github.com/pikaqiu112/Sunert_scripts/Scripts.git ~/Scripts
      -名称：使用 Node.js 12.x
        使用：操作/设置节点@v1
        与：
          节点版本：12.x
      -名称：npm 安装
        如果：env.YOUTH_HEADER
        运行：|
          cd ~/脚本
          npm 安装
      -名称：'运行【中青看点】'
        如果：env.YOUTH_HEADER
        运行：|
          cd ~/脚本
          节点任务/youth.js
        环境：
          YOUTH_NOTIFY_CONTROL : ${{ 秘密.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY : ${{ 秘密.PUSH_KEY }}
          BARK_PUSH : ${{ 秘密.BARK_PUSH }}
          TG_BOT_TOKEN : ${{ 秘密.TG_BOT_TOKEN }}
          TG_USER_ID : ${{ 秘密.TG_USER_ID }}
          BARK_SOUND : ${{ 秘密.BARK_SOUND }}
          DD_BOT_TOKEN : ${{ 秘密.DD_BOT_TOKEN }}
          DD_BOT_SECRET : ${{ 秘密.DD_BOT_SECRET }}
